addSbtPlugin("ch.epfl.scala"       % "sbt-scalafix"     % "0.14.3")
addSbtPlugin("org.jetbrains.scala" % "sbt-ide-settings" % "1.1.3")
addSbtPlugin("com.eed3si9n"        % "sbt-assembly"     % "2.3.1")
addSbtPlugin("org.scalameta"       % "sbt-scalafmt"     % "2.5.4")
addSbtPlugin("com.github.sbt"      % "sbt-dynver"       % "5.1.1")
addSbtPlugin("com.eed3si9n"        % "sbt-buildinfo"    % "0.13.1")
