# SPDX-License-Identifier: MIT
# Copyright: 2026 NiceBots.xyz
name: Quality Checks
on:
  workflow_call:

jobs:
  checks:
    name: "Scalafmt + Scalafix"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Set up Java
        uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5.2.0
        with:
          distribution: temurin
          java-version-file: .java-version
          check-latest: false
          cache: sbt

      - uses: sbt/setup-sbt@af116cce31c00823d3903ce687f9cda3a4f19f1b # v1.2.1
        with:
          disk-cache: false

      - name: Scalafmt Check
        run: sbt scalafmtCheckAll

      - name: Scalafix Check
        run: sbt "scalafixAll --check"

  test:
    name: "Tests (${{ matrix.os }})"
    needs: checks
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Set up Java
        uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5.2.0
        with:
          distribution: temurin
          java-version-file: .java-version
          check-latest: false
          cache: sbt

      - uses: sbt/setup-sbt@af116cce31c00823d3903ce687f9cda3a4f19f1b # v1.2.1
        with:
          disk-cache: false

      - name: Test
        run: sbt test
